# Bun Configuration for Suplementor
# Optimized for Next.js 15, TypeScript 5.8+, and Polish educational platform

[install]
# Use Bun's native package manager
registry = "https://registry.npmjs.org/"
cache = "~/.bun/install/cache"

# Optimize for performance
production = false
optional = true
dev = true
peer = true

# Lockfile configuration
lockfile = true
exact = false

[install.scopes]
# Configure scoped registries if needed

[run]
# Shell configuration for scripts
# Use 'system' for Netlify compatibility (bash not supported in Bun on Netlify)
shell = "system"
bun = true

[test]
# Test configuration
preload = ["./vitest.setup.ts"]
coverage = true

[build]
# Build optimizations
minify = true
sourcemap = "external"
target = "browser"

